---
commandPrefix: !
defaultChannel: "#radio"
adminMask: "*!*@staff/*"

hostname: localhost
nickname: radiod
port: 6697
realName: Radio LizardNet
servicesCertificate: radiod.pfx

serverPassword: ""
operUser: ""
operPass: ""

myQueue: reply
requestQueue: request

streamName: radio

rabbitMqConfiguration:
  objectPrefix: radiolizardnet.
  hostname: localhost
  port: 5672
  virtualHost: /
  username: guest
  password: guest
  tls: false

awsConfiguration:
  profile: default
  bucketName: radiod-bucket
  voices:
    # en-US
    - Danielle
    - Gregory
    - Kevin
    - Salli
    - Matthew
    - Kimberly
    - Kendra
    - Justin
    - Joey
    - Joanna
    - Ivy
    - Ruth
    - Stephen
    # en-GB
    - Emma
    - Brian
    - Amy
    - Arthur
    # en-AU
    - Olivia
    # en-NZ
    - Aria
    # en-IE
    - Niamh
    # en-IN
    - Kajal
    # en-ZA
    - Ayanda