name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
    - uses: docker/setup-buildx-action@v3

    - uses: actions/checkout@v4

    - name: Set outputs
      id: vars
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "timestamp=$(date --iso=seconds | sed -re s/[-:]//g -e 's/\+.*//')" >> $GITHUB_OUTPUT

    - name: Metadata for bot
      id: meta-bot
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/stwalkerster/radiod
        tags: |
          type=raw,value=bot,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
          type=ref,event=pr,prefix=bot-pr-
          type=sha,prefix=bot-

    - name: Metadata for sidecar
      id: meta-sidecar
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/stwalkerster/radiod
        tags: |
          type=raw,value=sidecar,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
          type=ref,event=pr,prefix=sidecar-pr-
          type=sha,prefix=sidecar-

    - name: Metadata for metadata monitor
      id: meta-metadata
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/stwalkerster/radiod
        tags: |
          type=raw,value=metadata,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
          type=ref,event=pr,prefix=metadata-pr-
          type=sha,prefix=metadata-

    - name: Metadata for announcer
      id: meta-announcer
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/stwalkerster/radiod
        tags: |
          type=raw,value=announcer,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
          type=ref,event=pr,prefix=announcer-pr-
          type=sha,prefix=announcer-

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish rail announcer
      run: dotnet publish LizardNetRadio.RailAnnouncer/LizardNetRadio.RailAnnouncer.csproj

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-1
        role-to-assume: arn:aws:iam::098014529583:role/github-actions/gha-artefacts-upload
        role-session-name: stwalkerster-radiod

    - name: Package and upload
      run: |
        cd LizardNetRadio.Bot/bin/Debug
        mv net8.0 radiod-bot
        tar czf radiod-bot.tar.gz radiod-bot/
        aws s3 cp radiod-bot.tar.gz s3://stwalkerster-098014529583-github-artefacts/stwalkerster/radiod/${{ steps.vars.outputs.timestamp }}-${{ steps.vars.outputs.sha_short }}/

        cd ../../../LizardNetRadio.Sidecar/bin/Debug
        mv net8.0 radiod-sidecar
        tar czf radiod-sidecar.tar.gz radiod-sidecar/
        aws s3 cp radiod-sidecar.tar.gz s3://stwalkerster-098014529583-github-artefacts/stwalkerster/radiod/${{ steps.vars.outputs.timestamp }}-${{ steps.vars.outputs.sha_short }}/

        cd ../../../LizardNetRadio.MetadataMonitor/bin/Debug
        mv net8.0 radiod-metadata
        tar czf radiod-metadata.tar.gz radiod-metadata/
        aws s3 cp radiod-metadata.tar.gz s3://stwalkerster-098014529583-github-artefacts/stwalkerster/radiod/${{ steps.vars.outputs.timestamp }}-${{ steps.vars.outputs.sha_short }}/

        cd ../../../LizardNetRadio.RailAnnouncer/bin/Release/net8.0
        mv publish radiod-announcer
        tar czf radiod-announcer.tar.gz radiod-announcer/
        aws s3 cp radiod-announcer.tar.gz s3://stwalkerster-098014529583-github-artefacts/stwalkerster/radiod/${{ steps.vars.outputs.timestamp }}-${{ steps.vars.outputs.sha_short }}/

    - name: GHCR login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: stwalkerster
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Bot Docker image
      uses: docker/build-push-action@v6
      with:
        context: LizardNetRadio.Bot/bin/Debug/radiod-bot/
        push: true
        labels: ${{ steps.meta-bot.outputs.labels }}
        tags:  ${{ steps.meta-bot.outputs.tags }}
        build-args: |
          GIT_VERSION_HASH=${{ github.sha }}

    - name: Build Sidecar Docker image
      uses: docker/build-push-action@v6
      with:
        context: LizardNetRadio.Sidecar/bin/Debug/radiod-sidecar/
        push: true
        labels: ${{ steps.meta-sidecar.outputs.labels }}
        tags:  ${{ steps.meta-sidecar.outputs.tags }}
        build-args: |
          GIT_VERSION_HASH=${{ github.sha }}

    - name: Build Metadata Monitor Docker image
      uses: docker/build-push-action@v6
      with:
        context: LizardNetRadio.MetadataMonitor/bin/Debug/radiod-metadata/
        push: true
        labels: ${{ steps.meta-metadata.outputs.labels }}
        tags:  ${{ steps.meta-metadata.outputs.tags }}
        build-args: |
          GIT_VERSION_HASH=${{ github.sha }}
